# Generated by Django 5.0.4 on 2024-04-23 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_description',
            field=models.CharField(blank=True, default='', max_length=250000, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_fix_or_percentage',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_min_order_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_scope_user',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_scope_user_group',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_stop_other_discounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Loyalty', 'Loyalty'), ('Volume', 'Volume'), ('Credit', 'Credit'), ('Product type', 'Product type'), ('Promotion', 'Promotion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_use_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_use_limit_per_user',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_validity_end',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_validity_start',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, null=True)),
                ('brand_visible', models.BooleanField(default=False)),
                ('brand_description', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='uploads/brand/')),
                ('brand_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('brand_url', models.URLField(blank=True, null=True)),
                ('brand_allowed_groups', models.ManyToManyField(blank=True, related_name='brand_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_scope_brand',
            field=models.ManyToManyField(blank=True, related_name='brands', to='coupons.brand'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('category_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('category_url', models.URLField(blank=True, null=True)),
                ('category_visible', models.BooleanField(default=False)),
                ('category_parent', models.CharField(blank=True, max_length=50, null=True)),
                ('category_description', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='uploads/category/')),
                ('category_allowed_groups', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_scope_category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='coupons.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=250000, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('manufacturer_reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('media', models.ImageField(null=True, upload_to='uploads/product/')),
                ('stock', models.IntegerField(default=0)),
                ('stock_min_qty_alert', models.IntegerField(default=0)),
                ('min_order_qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('hashtag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dim_height', models.IntegerField(default=0)),
                ('dim_width', models.IntegerField(default=0)),
                ('dim_debt', models.IntegerField(default=0)),
                ('dim_weight', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='coupons.brand')),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='coupons.category')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_scope_product',
            field=models.ManyToManyField(blank=True, related_name='products', to='coupons.product'),
        ),
    ]
