# Generated by Django 5.0.4 on 2024-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_remove_product_category_remove_product_brand_and_more'),
        ('shop', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_scope_brand',
            field=models.ManyToManyField(blank=True, related_name='brands', to='shop.brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
